name: Run and Check Node.js Code
description: Run and Check Node.js Code

runs:
    using: composite
    steps:
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'yarn'
        - run: yarn install --immutable --immutable-cache --check-cache
          shell: bash
        - run: yarn format:ci
          shell: bash
        - run: yarn lint:ci
          shell: bash
        - run: yarn build
          shell: bash
        # - run: yarn test:ci
        #   shell: bash
